workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-gh-pages

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  docker:
    repo: plugins/gh-pages
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: GitHub Pages
  desc: Copies a directory to GitHub Pages
  type: publish
  image: plugins/gh-pages
  labels:
    - github
    - pages
