pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-gh-pages
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: GitHub Pages
  desc: Copies a directory to GitHub Pages
  type: publish
  image: plugins/drone-gh-pages
  labels:
    - github
    - pages
